// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "项目维护者",
            "url": "https://github.com/xiebiao/bookstore",
            "email": "xiebiao@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "description": "分页查询图书列表，支持关键词搜索和排序（公开接口，无需登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图书模块"
                ],
                "summary": "图书列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码（默认1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量（默认20，最大100）",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词（匹配标题/作者/出版社）",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "price_asc",
                            "price_desc",
                            "created_at_desc"
                        ],
                        "type": "string",
                        "default": "created_at_desc",
                        "description": "排序方式",
                        "name": "sort_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.ListBooksResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误（如page_size超过100）",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "会员发布图书商品上架（需要登录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图书模块"
                ],
                "summary": "发布图书",
                "parameters": [
                    {
                        "description": "图书信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.PublishBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上架成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.BookResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误（如ISBN格式错误、价格超出范围）",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    },
                    "409": {
                        "description": "ISBN已存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/orders": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户下单购买图书（需要登录），使用悲观锁防止超卖",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单模块"
                ],
                "summary": "创建订单",
                "parameters": [
                    {
                        "description": "订单信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "下单成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.CreateOrderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误（如商品数量超过999）",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "图书不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    },
                    "50001": {
                        "description": "库存不足",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "验证邮箱密码，返回JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回access_token和refresh_token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "邮箱或密码错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "创建新用户账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    },
                    "409": {
                        "description": "邮箱已存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_xiebiao_bookstore_pkg_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_xiebiao_bookstore_internal_interface_http_dto.BookListItem": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "威廉·肯尼迪"
                },
                "cover_url": {
                    "type": "string",
                    "example": "https://example.com/cover.jpg"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15 10:30:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "isbn": {
                    "type": "string",
                    "example": "9787115428028"
                },
                "price": {
                    "type": "integer",
                    "example": 5900
                },
                "price_yuan": {
                    "type": "string",
                    "example": "59.00"
                },
                "publisher": {
                    "type": "string",
                    "example": "人民邮电出版社"
                },
                "stock": {
                    "type": "integer",
                    "example": 100
                },
                "title": {
                    "type": "string",
                    "example": "Go语言实战"
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.BookResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "威廉·肯尼迪"
                },
                "cover_url": {
                    "type": "string",
                    "example": "https://example.com/cover.jpg"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15 10:30:00"
                },
                "description": {
                    "type": "string",
                    "example": "这是一本关于Go语言的实战书籍"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "isbn": {
                    "type": "string",
                    "example": "9787115428028"
                },
                "price": {
                    "description": "价格(分)",
                    "type": "integer",
                    "example": 5900
                },
                "price_yuan": {
                    "description": "价格(元),方便前端显示",
                    "type": "string",
                    "example": "59.00"
                },
                "publisher": {
                    "type": "string",
                    "example": "人民邮电出版社"
                },
                "publisher_id": {
                    "type": "integer",
                    "example": 1
                },
                "stock": {
                    "type": "integer",
                    "example": 100
                },
                "title": {
                    "type": "string",
                    "example": "Go语言实战"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-15 10:30:00"
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.CreateOrderItemRequest": {
            "type": "object",
            "required": [
                "book_id",
                "quantity"
            ],
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer",
                    "maximum": 999,
                    "minimum": 1
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.CreateOrderRequest": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.CreateOrderItemRequest"
                    }
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.CreateOrderResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-11-06 10:30:00"
                },
                "order_id": {
                    "type": "integer",
                    "example": 1
                },
                "order_no": {
                    "type": "string",
                    "example": "ORD1699248000123456"
                },
                "status": {
                    "type": "string",
                    "example": "待支付"
                },
                "total": {
                    "type": "integer",
                    "example": 11800
                },
                "total_yuan": {
                    "type": "string",
                    "example": "118.00"
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.ListBooksResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.BookListItem"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_xiebiao_bookstore_internal_interface_http_dto.UserInfo"
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.PublishBookRequest": {
            "type": "object",
            "required": [
                "author",
                "isbn",
                "price",
                "publisher",
                "title"
            ],
            "properties": {
                "author": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "威廉·肯尼迪"
                },
                "cover_url": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "https://example.com/cover.jpg"
                },
                "description": {
                    "type": "string",
                    "maxLength": 5000,
                    "example": "这是一本关于Go语言的实战书籍"
                },
                "isbn": {
                    "type": "string",
                    "example": "9787115428028"
                },
                "price": {
                    "description": "价格(分),59.00元",
                    "type": "integer",
                    "maximum": 999999,
                    "minimum": 1,
                    "example": 5900
                },
                "publisher": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "人民邮电出版社"
                },
                "stock": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 100
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "example": "Go语言实战"
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "nickname",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 8
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.UserInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "github_com_xiebiao_bookstore_internal_interface_http_dto.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "github_com_xiebiao_bookstore_pkg_response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "输入\"Bearer {token}\"进行身份验证",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "图书商城API文档",
	Description:      "这是一个教学导向的Go微服务实战项目的API文档\n本项目演示了DDD分层架构、Wire依赖注入、防超卖等核心技术",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
