// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: proto/inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 查询库存
type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        uint64                 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockRequest) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BookId        uint64                 `protobuf:"varint,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"` // 库存数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetStockResponse) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *GetStockResponse) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

// 批量查询库存
type BatchGetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookIds       []uint64               `protobuf:"varint,1,rep,packed,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetStockRequest) Reset() {
	*x = BatchGetStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetStockRequest) ProtoMessage() {}

func (x *BatchGetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetStockRequest.ProtoReflect.Descriptor instead.
func (*BatchGetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetStockRequest) GetBookIds() []uint64 {
	if x != nil {
		return x.BookIds
	}
	return nil
}

type BatchGetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stocks        []*StockInfo           `protobuf:"bytes,3,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetStockResponse) Reset() {
	*x = BatchGetStockResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetStockResponse) ProtoMessage() {}

func (x *BatchGetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetStockResponse.ProtoReflect.Descriptor instead.
func (*BatchGetStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetStockResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchGetStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchGetStockResponse) GetStocks() []*StockInfo {
	if x != nil {
		return x.Stocks
	}
	return nil
}

// 库存信息
type StockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        uint64                 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfo) Reset() {
	*x = StockInfo{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfo) ProtoMessage() {}

func (x *StockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfo.ProtoReflect.Descriptor instead.
func (*StockInfo) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *StockInfo) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *StockInfo) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

// 扣减库存
type DeductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        uint64                 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`              // 扣减数量
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单ID（用于幂等性控制）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockRequest) Reset() {
	*x = DeductStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockRequest) ProtoMessage() {}

func (x *DeductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockRequest.ProtoReflect.Descriptor instead.
func (*DeductStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *DeductStockRequest) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *DeductStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DeductStockRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type DeductStockResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0成功，1库存不足，2其他错误
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RemainingStock int32                  `protobuf:"varint,3,opt,name=remaining_stock,json=remainingStock,proto3" json:"remaining_stock,omitempty"` // 扣减后剩余库存
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeductStockResponse) Reset() {
	*x = DeductStockResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResponse) ProtoMessage() {}

func (x *DeductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResponse.ProtoReflect.Descriptor instead.
func (*DeductStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *DeductStockResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeductStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeductStockResponse) GetRemainingStock() int32 {
	if x != nil {
		return x.RemainingStock
	}
	return 0
}

// 释放库存
type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        uint64                 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单ID（用于记录日志）
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                   // 释放原因：order_cancelled, payment_failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseStockRequest) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *ReleaseStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReleaseStockRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReleaseStockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentStock  int32                  `protobuf:"varint,3,opt,name=current_stock,json=currentStock,proto3" json:"current_stock,omitempty"` // 释放后当前库存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockResponse) Reset() {
	*x = ReleaseStockResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse) ProtoMessage() {}

func (x *ReleaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseStockResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReleaseStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReleaseStockResponse) GetCurrentStock() int32 {
	if x != nil {
		return x.CurrentStock
	}
	return 0
}

// 补充库存
type RestockInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        uint64                 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"` // 补充数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockInventoryRequest) Reset() {
	*x = RestockInventoryRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockInventoryRequest) ProtoMessage() {}

func (x *RestockInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockInventoryRequest.ProtoReflect.Descriptor instead.
func (*RestockInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *RestockInventoryRequest) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *RestockInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RestockInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentStock  int32                  `protobuf:"varint,3,opt,name=current_stock,json=currentStock,proto3" json:"current_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockInventoryResponse) Reset() {
	*x = RestockInventoryResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockInventoryResponse) ProtoMessage() {}

func (x *RestockInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockInventoryResponse.ProtoReflect.Descriptor instead.
func (*RestockInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *RestockInventoryResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RestockInventoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RestockInventoryResponse) GetCurrentStock() int32 {
	if x != nil {
		return x.CurrentStock
	}
	return 0
}

// 获取库存变更日志
type GetInventoryLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        uint64                 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryLogsRequest) Reset() {
	*x = GetInventoryLogsRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryLogsRequest) ProtoMessage() {}

func (x *GetInventoryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryLogsRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *GetInventoryLogsRequest) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *GetInventoryLogsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetInventoryLogsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetInventoryLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Logs          []*InventoryLog        `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryLogsResponse) Reset() {
	*x = GetInventoryLogsResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryLogsResponse) ProtoMessage() {}

func (x *GetInventoryLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryLogsResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *GetInventoryLogsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetInventoryLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetInventoryLogsResponse) GetLogs() []*InventoryLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetInventoryLogsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 库存变更日志
type InventoryLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        uint64                 `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChangeType    string                 `protobuf:"bytes,3,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`     // DEDUCT, RELEASE, RESTOCK
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                          // 变更数量（正数为增加，负数为减少）
	BeforeStock   int32                  `protobuf:"varint,5,opt,name=before_stock,json=beforeStock,proto3" json:"before_stock,omitempty"` // 变更前库存
	AfterStock    int32                  `protobuf:"varint,6,opt,name=after_stock,json=afterStock,proto3" json:"after_stock,omitempty"`    // 变更后库存
	OrderId       uint64                 `protobuf:"varint,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`             // 关联订单ID（可选）
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryLog) Reset() {
	*x = InventoryLog{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryLog) ProtoMessage() {}

func (x *InventoryLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryLog.ProtoReflect.Descriptor instead.
func (*InventoryLog) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *InventoryLog) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InventoryLog) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *InventoryLog) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *InventoryLog) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InventoryLog) GetBeforeStock() int32 {
	if x != nil {
		return x.BeforeStock
	}
	return 0
}

func (x *InventoryLog) GetAfterStock() int32 {
	if x != nil {
		return x.AfterStock
	}
	return 0
}

func (x *InventoryLog) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *InventoryLog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_proto_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\"proto/inventory/v1/inventory.proto\x12\finventory.v1\"*\n" +
	"\x0fGetStockRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x04R\x06bookId\"o\n" +
	"\x10GetStockResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\x04R\x06bookId\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\"1\n" +
	"\x14BatchGetStockRequest\x12\x19\n" +
	"\bbook_ids\x18\x01 \x03(\x04R\abookIds\"v\n" +
	"\x15BatchGetStockResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x06stocks\x18\x03 \x03(\v2\x17.inventory.v1.StockInfoR\x06stocks\":\n" +
	"\tStockInfo\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x04R\x06bookId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock\"d\n" +
	"\x12DeductStockRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x04R\x06bookId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\"l\n" +
	"\x13DeductStockResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fremaining_stock\x18\x03 \x01(\x05R\x0eremainingStock\"}\n" +
	"\x13ReleaseStockRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x04R\x06bookId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"i\n" +
	"\x14ReleaseStockResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcurrent_stock\x18\x03 \x01(\x05R\fcurrentStock\"N\n" +
	"\x17RestockInventoryRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x04R\x06bookId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"m\n" +
	"\x18RestockInventoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcurrent_stock\x18\x03 \x01(\x05R\fcurrentStock\"c\n" +
	"\x17GetInventoryLogsRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x04R\x06bookId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"\x8e\x01\n" +
	"\x18GetInventoryLogsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04logs\x18\x03 \x03(\v2\x1a.inventory.v1.InventoryLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"\xf2\x01\n" +
	"\fInventoryLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x04R\x06bookId\x12\x1f\n" +
	"\vchange_type\x18\x03 \x01(\tR\n" +
	"changeType\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12!\n" +
	"\fbefore_stock\x18\x05 \x01(\x05R\vbeforeStock\x12\x1f\n" +
	"\vafter_stock\x18\x06 \x01(\x05R\n" +
	"afterStock\x12\x19\n" +
	"\border_id\x18\a \x01(\x04R\aorderId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt2\xa8\x04\n" +
	"\x10InventoryService\x12I\n" +
	"\bGetStock\x12\x1d.inventory.v1.GetStockRequest\x1a\x1e.inventory.v1.GetStockResponse\x12X\n" +
	"\rBatchGetStock\x12\".inventory.v1.BatchGetStockRequest\x1a#.inventory.v1.BatchGetStockResponse\x12R\n" +
	"\vDeductStock\x12 .inventory.v1.DeductStockRequest\x1a!.inventory.v1.DeductStockResponse\x12U\n" +
	"\fReleaseStock\x12!.inventory.v1.ReleaseStockRequest\x1a\".inventory.v1.ReleaseStockResponse\x12a\n" +
	"\x10RestockInventory\x12%.inventory.v1.RestockInventoryRequest\x1a&.inventory.v1.RestockInventoryResponse\x12a\n" +
	"\x10GetInventoryLogs\x12%.inventory.v1.GetInventoryLogsRequest\x1a&.inventory.v1.GetInventoryLogsResponseB=Z;github.com/xiebiao/bookstore/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_proto_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_v1_inventory_proto_rawDescData []byte
)

func file_proto_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_v1_inventory_proto_rawDescData
}

var file_proto_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_inventory_v1_inventory_proto_goTypes = []any{
	(*GetStockRequest)(nil),          // 0: inventory.v1.GetStockRequest
	(*GetStockResponse)(nil),         // 1: inventory.v1.GetStockResponse
	(*BatchGetStockRequest)(nil),     // 2: inventory.v1.BatchGetStockRequest
	(*BatchGetStockResponse)(nil),    // 3: inventory.v1.BatchGetStockResponse
	(*StockInfo)(nil),                // 4: inventory.v1.StockInfo
	(*DeductStockRequest)(nil),       // 5: inventory.v1.DeductStockRequest
	(*DeductStockResponse)(nil),      // 6: inventory.v1.DeductStockResponse
	(*ReleaseStockRequest)(nil),      // 7: inventory.v1.ReleaseStockRequest
	(*ReleaseStockResponse)(nil),     // 8: inventory.v1.ReleaseStockResponse
	(*RestockInventoryRequest)(nil),  // 9: inventory.v1.RestockInventoryRequest
	(*RestockInventoryResponse)(nil), // 10: inventory.v1.RestockInventoryResponse
	(*GetInventoryLogsRequest)(nil),  // 11: inventory.v1.GetInventoryLogsRequest
	(*GetInventoryLogsResponse)(nil), // 12: inventory.v1.GetInventoryLogsResponse
	(*InventoryLog)(nil),             // 13: inventory.v1.InventoryLog
}
var file_proto_inventory_v1_inventory_proto_depIdxs = []int32{
	4,  // 0: inventory.v1.BatchGetStockResponse.stocks:type_name -> inventory.v1.StockInfo
	13, // 1: inventory.v1.GetInventoryLogsResponse.logs:type_name -> inventory.v1.InventoryLog
	0,  // 2: inventory.v1.InventoryService.GetStock:input_type -> inventory.v1.GetStockRequest
	2,  // 3: inventory.v1.InventoryService.BatchGetStock:input_type -> inventory.v1.BatchGetStockRequest
	5,  // 4: inventory.v1.InventoryService.DeductStock:input_type -> inventory.v1.DeductStockRequest
	7,  // 5: inventory.v1.InventoryService.ReleaseStock:input_type -> inventory.v1.ReleaseStockRequest
	9,  // 6: inventory.v1.InventoryService.RestockInventory:input_type -> inventory.v1.RestockInventoryRequest
	11, // 7: inventory.v1.InventoryService.GetInventoryLogs:input_type -> inventory.v1.GetInventoryLogsRequest
	1,  // 8: inventory.v1.InventoryService.GetStock:output_type -> inventory.v1.GetStockResponse
	3,  // 9: inventory.v1.InventoryService.BatchGetStock:output_type -> inventory.v1.BatchGetStockResponse
	6,  // 10: inventory.v1.InventoryService.DeductStock:output_type -> inventory.v1.DeductStockResponse
	8,  // 11: inventory.v1.InventoryService.ReleaseStock:output_type -> inventory.v1.ReleaseStockResponse
	10, // 12: inventory.v1.InventoryService.RestockInventory:output_type -> inventory.v1.RestockInventoryResponse
	12, // 13: inventory.v1.InventoryService.GetInventoryLogs:output_type -> inventory.v1.GetInventoryLogsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_inventory_v1_inventory_proto_init() }
func file_proto_inventory_v1_inventory_proto_init() {
	if File_proto_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_v1_inventory_proto = out.File
	file_proto_inventory_v1_inventory_proto_goTypes = nil
	file_proto_inventory_v1_inventory_proto_depIdxs = nil
}
